version: '3'
services:
  # laravel
  app:
    build: ./docker/app
    container_name: app
    volumes:
      - ./src/laravel:/var/www/html
    ports:
      - 80:80

  # MySQL
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      TZ: 'Asia/Tokyo'
    # Command at start
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    
  smtp:
      image: schickling/mailcatcher
      container_name: smtp
      ports:
        - "1080:1080"
        - "1025:1025"

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
        - PMA_HOST=db
      links:
        - db
      ports:
        - 8008:80
      volumes:
        - ./docker/no/phpmyadmin/sessions:/sessions